import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,Bot,BarChart3,Folder,Settings,Radio,Play,Pause,RotateCcw,ChevronDown,Volume2,Camera,Maximize2,Sparkles,Zap,AlertTriangle,CheckCircle2,Send,SlidersHorizontal,CircleStop,Box,Plus,Search,MoreHorizontal,Upload,FileText,Image,Video,Music,User,LockKeyhole,Eye,EyeOff,Smartphone,ArrowRight,ShieldCheck,RefreshCw,Bell,Headphones,Mic2,Activity,TrendingUp,Users,ShoppingCart,CalendarDays,Download,Edit3,Save,X,Check,ChevronRight,LogOut,HelpCircle}from'lucide-react';
import'./styles.css';

const NAV=[[Home,'工作台','workspace'],[Bot,'助手配置','assistant'],[BarChart3,'直播复盘','review'],[Folder,'素材中心','assets'],[Settings,'设置','settings']];
const products=[['清爽控油精华液','30ml','199','532','#d8c8b5'],['保湿修护水乳套装','套装','299','386','#eef0f4'],['舒缓修护面膜','5片','129','761','#e8e2dc'],['氨基酸洁面乳','120g','89','1243','#dbdfe8']];
const messages=[['小雨点','这个适合油皮吗？','粉丝1','12:34:52'],['爱购物的猫','有没有赠品呀','粉丝团','12:34:53'],['系统消息','3分钟福袋倒计时已开始','公告','12:34:56'],['甜心小丸子','已拍1号链接','粉丝2','12:34:57'],['云起小助手','@小雨点 这款精华油皮也可以放心用哦～','助手','12:34:58']];

function Logo({compact=false}){return <div className={'brand '+(compact?'compact':'')}><img src="/assets/standard-logo-dark.png" alt="云起慧播"/>{!compact&&<span>AI直播工作台</span>}</div>}
function Auth({mode,setMode,onSuccess}){const[show,setShow]=useState(false),[step,setStep]=useState(1),[agree,setAgree]=useState(true);const login=mode==='login';function submit(e){e.preventDefault();if(!agree)return;if(login||step===2)onSuccess();else setStep(2)}return <div className="auth-screen"><div className="auth-brand"><Logo/><div className="auth-message"><h1>让一个人，也能掌控一场专业直播</h1><p>AI 实时识别、智能搭话与直播动作协同执行，让直播运营更稳定、更高效。</p><div className="auth-proof">{['实时识别','智能控场','数据复盘'].map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div></div><div className="signal-orbit"><i/><i/><i/></div></div><div className="auth-panel"><form onSubmit={submit}><div className="auth-top"><Logo compact/><span>2.0</span></div><h2>{login?'欢迎回来':'创建云起慧播账号'}</h2><p>{login?'登录后继续管理你的直播间和 AI 助手':step===1?'只需两步，即可开始搭建你的 AI 直播间':'设置账号信息，完成注册'}</p>{!login&&<div className="steps"><span className="done">1</span><i/><span className={step===2?'done':''}>2</span><em>{step===1?'验证手机号':'设置账号'}</em></div>}{(login||step===1)&&<><label>手机号</label><div className="field"><Smartphone/><input type="tel" defaultValue={login?'138 0013 8000':''} placeholder="请输入手机号"/></div></>}{login&&<><label>登录密码</label><div className="field"><LockKeyhole/><input type={show?'text':'password'} defaultValue="12345678" placeholder="请输入密码"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div><div className="form-options"><label><input type="checkbox" defaultChecked/>保持登录</label><button type="button">忘记密码？</button></div></>}{!login&&step===1&&<><label>短信验证码</label><div className="field code"><ShieldCheck/><input placeholder="请输入 6 位验证码"/><button type="button">获取验证码</button></div></>}{!login&&step===2&&<><label>昵称</label><div className="field"><User/><input placeholder="例如：小云运营"/></div><label>设置密码</label><div className="field"><LockKeyhole/><input type={show?'text':'password'} placeholder="8-20 位，包含字母和数字"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div><div className="strength"><i/><i/><i/><span>密码强度：建议使用字母、数字组合</span></div></>}<label className="agreement"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>我已阅读并同意《用户协议》和《隐私政策》</label><button className="auth-submit" disabled={!agree}>{login?'登录':step===1?'下一步':'完成注册'}<ArrowRight/></button><div className="auth-switch">{login?'还没有账号？':'已有账号？'}<button type="button" onClick={()=>{setMode(login?'register':'login');setStep(1)}}>{login?'立即注册':'返回登录'}</button></div></form><footer>Windows 10 / 11　·　版本 2.0.0　·　联系客服</footer></div></div>}

function AuthV2({mode,setMode,onSuccess}){const[show,setShow]=useState(false),[step,setStep]=useState(1),[agree,setAgree]=useState(true);const login=mode==='login';function submit(e){e.preventDefault();if(!agree)return;if(login||step===2)onSuccess();else setStep(2)}return <div className="auth-v2"><div className="auth-window"><Logo/><div className="window-actions"><span>—</span><span>□</span><span>×</span></div></div><section className="auth-visual"><div className="auth-title"><h1>云起慧播</h1><p>让每一次直播都更有价值</p></div><div className="visual-features">{[[BarChart3,'高清流畅'],[Users,'全球覆盖'],[User,'互动实时'],[ShieldCheck,'安全稳定']].map(([I,x])=><span key={x}><I/>{x}</span>)}</div></section><section className="auth-card"><form onSubmit={submit}><h2>{login?'欢迎使用云起慧播':'创建云起慧播账号'}</h2><p>{login?'登录开启您的直播之旅':step===1?'验证手机号，开启您的直播之旅':'设置账号信息，完成注册'}</p>{!login&&<div className="steps"><span className="done">1</span><i/><span className={step===2?'done':''}>2</span><em>{step===1?'验证手机号':'设置账号'}</em></div>}{(login||step===1)&&<><label>{login?'账号':'手机号'}</label><div className="field"><User/><input type="tel" placeholder={login?'请输入账号':'请输入手机号'}/></div></>}{login&&<><label>密码</label><div className="field"><LockKeyhole/><input type={show?'text':'password'} placeholder="请输入密码"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div><div className="form-options"><label><input type="checkbox"/>记住密码</label><button type="button">忘记密码？</button></div></>}{!login&&step===1&&<><label>短信验证码</label><div className="field code"><ShieldCheck/><input placeholder="请输入 6 位验证码"/><button type="button">获取验证码</button></div></>}{!login&&step===2&&<><label>昵称</label><div className="field"><User/><input placeholder="请输入昵称"/></div><label>设置密码</label><div className="field"><LockKeyhole/><input type={show?'text':'password'} placeholder="8-20 位，包含字母和数字"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></>}<button className="auth-submit" disabled={!agree}>{login?'登录':step===1?'下一步':'完成注册'}</button>{login&&<><div className="other-login"><i/>其他登录方式<i/></div><button type="button" className="phone-login"><Smartphone/></button></>}<div className="auth-switch">{login?'还没有账号？':'已有账号？'}<button type="button" onClick={()=>{setMode(login?'register':'login');setStep(1)}}>{login?'立即注册':'返回登录'}</button></div><label className="agreement"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>登录即代表您已阅读并同意《用户协议》和《隐私政策》</label></form></section></div>}

function Sidebar({page,setPage,onLogout}){return <aside><Logo/><nav>{NAV.map(([I,label,id])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><I/><span>{label}</span></button>)}</nav><div className="side-bottom"><button><HelpCircle/><span>帮助中心</span></button><button onClick={onLogout}><LogOut/><span>退出登录</span></button></div></aside>}
function AppHeader({page}){const name=NAV.find(x=>x[2]===page)?.[1];return <header className="app-header"><div><h1>{name}</h1><p>{page==='workspace'?'实时掌握直播状态与 AI 执行进度':'云起慧播 2.0 · '+name}</p></div><div className="header-actions"><button className="status"><span/>服务运行正常</button><button aria-label="消息"><Bell/></button><button className="avatar">云</button><div className="user-meta"><strong>小云运营</strong><span>专业版</span></div><ChevronDown/></div></header>}
function SelectBlock({icon:I,title,children}){return <div className="select-block"><I/><div><small>{title}</small><strong>{children}</strong></div><ChevronDown/></div>}
function CommandBar({live,setLive}){return <div className="command-bar"><SelectBlock icon={Radio} title="抖音直播间"><span>云起官方直播间</span><em>直播间已连接</em></SelectBlock><SelectBlock icon={Bot} title="当前助手">默认AI助播（专业版）</SelectBlock><div className="ai-state"><span className="wave">▮▮▮</span><div><small>AI助播状态</small><strong>AI助播运行中</strong></div></div><button className="test"><Play/>模拟测试</button><button className={'go-live '+(live?'is-live':'')} onClick={()=>setLive(!live)}>{live?<CircleStop/>:<Radio/>}{live?'结束直播':'正式开播'}</button></div>}
function Health(){return <div className="health section"><div className="section-head"><b>直播健康度</b><span>查看详情 ›</span></div><div className="metrics">{[['网络','优秀 ●'],['FPS','30'],['码率','2500'],['延迟','28 ms']].map((x,i)=><div key={x[0]}><small>{x[0]}</small><strong className={i===0?'good':''}>{x[1]}</strong></div>)}</div></div>}
function Device({camera=false}){return <div className="device section"><b>{camera?'摄像头':'音频输入'}</b><div className="device-select">{camera?'USB Camera':'麦克风 (Realtek(R) Audio)'}<ChevronDown/></div><div className="level">{camera?<div className="camera-thumb"><Camera/></div>:<div className="bars">▮▮▮▮▮▮▮▮▮</div>}<Volume2/><div className="range"><i style={{width:camera?'100%':'80%'}}/></div><span>{camera?'100%':'80%'}</span></div></div>}
function StreamPanel({paused,setPaused}){return <section className="left-panel"><div className="panel-title"><b>直播画面</b><span className="live-dot">● 直播中</span><time>00:12:36</time><Maximize2/></div><div className="video-stage"><div className="video-scene"><div className="ring"/><div className="person">云</div><div className="bottle"/></div><div className="video-stats"><b>直播中</b><span>◉ 1.2w</span><span>♥ 368</span></div></div><Health/><Device/><Device camera/><div className="assist-controls section"><b>助播控制</b><div><button className="primary" onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}{paused?'继续助播':'暂停助播'}</button><button><RotateCcw/>重置会话</button></div></div><div className="warning"><AlertTriangle/><span>检测到网络抖动，可能影响识别准确率</span><a>查看详情</a></div></section>}
function FlowCard({type,title,meta,children}){const I={listen:Sparkles,keyword:Zap,bot:Bot,action:Zap}[type];return <div className={'flow-card '+type}><div className="flow-label"><span><I/>{title}</span><em>{meta}</em></div>{children}</div>}
function AiFlow(){return <div className="flow"><FlowCard type="listen" title="当前说话内容（实时识别）" meta="置信度：0.96"><p className="speech">这款精华质地非常清爽，油皮用也不会觉得黏腻…</p></FlowCard><div className="connector">⌄</div><FlowCard type="keyword" title="命中关键词" meta="匹配规则：产品卖点-肤质适配"><div className="chips">{['精华','清爽','油皮','不黏腻'].map(x=><span key={x}>{x}</span>)}</div></FlowCard><div className="connector">⌄</div><FlowCard type="bot" title="AI搭话（即将回复）" meta="回复类型：卖点强化"><p>对的！这款精华专为油皮研发，清爽好吸收，不会闷痘～而且控油效果很棒！</p></FlowCard><div className="connector">⌄</div><FlowCard type="action" title="执行动作（已执行）"><div className="timeline">{[['发送弹窗','油皮挚爱！清爽不黏腻'],['展示商品卡片','清爽控油精华液 ¥199'],['设置福袋倒计时','3分钟倒计时已开启']].map(x=><div key={x[0]}><CheckCircle2/><time>12:34:56</time><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></FlowCard></div>}
function CenterPanel(){const[tab,setTab]=useState(0);return <main className="center-panel"><div className="tabs">{['实时识别','命中关键词','AI搭话','执行动作'].map((t,i)=><button onClick={()=>setTab(i)} className={tab===i?'active':''} key={t}>{t}</button>)}</div><AiFlow/><section className="script"><div className="section-head"><b>脚本提词</b><span>A−　A+　 标记</span></div><div><p>欢迎来到直播间！今天给大家带来我们的明星产品～</p><p className="current">这款精华是我们的畅销款，主打清爽控油，特别适合油皮和混油皮的姐妹～</p><p>核心成分能够有效改善出油、毛孔粗大等问题，坚持使用皮肤会更细腻！</p></div></section></main>}
function ProductPanel(){return <section className="products"><div className="section-head"><b>商品动作</b><span>管理商品 ›</span></div>{products.map(p=><div className="product" key={p[0]}><div className="product-img" style={{background:p[4]}}><Box/></div><div><strong>{p[0]} <i>{p[1]}</i></strong><em>¥{p[2]}</em><small>库存 {p[3]}</small></div><button>讲解</button><button className="secondary">上架</button></div>)}</section>}
function Messages(){const[f,setF]=useState(0);return <section className="messages"><div className="section-head"><b>互动消息</b><span><SlidersHorizontal/>筛选</span></div><div className="message-tabs">{['全部','用户消息','系统消息'].map((x,i)=><button key={x} className={f===i?'active':''} onClick={()=>setF(i)}>{x}</button>)}</div><div className="message-list">{messages.filter((_,i)=>f===0||(f===1&&i!==2&&i!==4)||(f===2&&(i===2||i===4))).map((m,i)=><div className="message" key={m[0]}><div className={'avatar a'+i}>{m[0][0]}</div><div><span>{m[0]} <em>{m[2]}</em></span><p>{m[1]}</p></div><time>{m[3]}</time></div>)}</div><div className="composer"><input placeholder="输入消息，回车发送"/><button aria-label="发送消息"><Send/></button></div></section>}
function Workspace(){const[paused,setPaused]=useState(false),[live,setLive]=useState(false);return <><CommandBar live={live} setLive={setLive}/><div className="workspace-grid"><StreamPanel paused={paused} setPaused={setPaused}/><CenterPanel/><div className="right-panel"><ProductPanel/><Messages/></div></div>{paused&&<div className="toast"><Pause/>AI 助播已暂停，直播画面仍保持运行</div>}</>}

function PageTop({title,desc,action,icon:I=Plus,onAction}){return <div className="page-top"><div><h2>{title}</h2><p>{desc}</p></div>{action&&<button className="primary-action" onClick={onAction}><I/>{action}</button>}</div>}
function AssistantPage(){const[selected,setSelected]=useState(0),[saved,setSaved]=useState(false);const list=['默认AI助播','美妆专场助手','大促活动助手'];return <div className="page-content"><PageTop title="助手配置" desc="在一个页面完成脚本、语音与直播动作设置" action="新建助手"/><div className="assistant-layout"><section className="list-pane"><div className="search"><Search/><input placeholder="搜索助手"/></div>{list.map((x,i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={x}><Bot/><span><strong>{x}</strong><small>{i===0?'正在使用 · 刚刚保存':'上次编辑 2 天前'}</small></span><MoreHorizontal/></button>)}<div className="list-help"><Sparkles/><b>配置建议</b><p>先完成基础话术，再添加关键词和动作，测试通过后即可开播。</p></div></section><section className="editor-pane"><div className="editor-head"><div><h3>{list[selected]}</h3><span><i/>自动保存已开启</span></div><button><Play/>模拟测试</button><button className="save" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1500)}}><Save/>{saved?'已保存':'保存配置'}</button></div><div className="editor-tabs"><button className="active">脚本与触发</button><button>商品互动</button><button>音色与语速</button><button>安全设置</button></div><div className="editor-body"><div className="script-list"><div className="subhead"><b>直播脚本</b><button><Plus/>添加话术</button></div>{['开场欢迎','产品引入','核心卖点','福利逼单'].map((x,i)=><div className={'script-row '+(i===2?'active':'')} key={x}><span>{i+1}</span><div><strong>{x}</strong><p>{['欢迎新进直播间的朋友，今天为大家准备了专属福利…','接下来给大家看看今天的主推产品…','这款精华质地清爽，尤其适合油皮和混油皮…','现在下单可享直播间专属价格，还有限量赠品…'][i]}</p></div><Edit3/></div>)}</div><div className="rule-panel"><div className="subhead"><b>“核心卖点”触发规则</b><span>已启用</span></div><label>触发关键词</label><div className="tag-input">{['清爽','油皮','不黏腻'].map(x=><span key={x}>{x}<X/></span>)}<input placeholder="输入后回车添加"/></div><label>AI 搭话内容</label><textarea defaultValue="对的！这款精华专为油皮研发，清爽好吸收，不会闷痘～"/><div className="form-grid"><div><label>音色</label><button className="select">云汐·活力女声<ChevronDown/></button></div><div><label>语速</label><button className="select">1.0x<ChevronDown/></button></div></div><label>同步执行动作</label><div className="action-checks"><button className="on"><Check/>展示商品卡片</button><button className="on"><Check/>发送弹幕</button><button><Plus/>添加动作</button></div></div></div></section></div></div>}

const sessions=[['8月28日 美妆专场','02:18:36','¥12,847','1,296','4.82'],['8月27日 晚间护肤专场','01:46:20','¥9,630','986','4.56'],['8月26日 新品首发','03:02:18','¥18,920','1,863','5.14'],['8月24日 周末大促','02:35:41','¥15,308','1,542','4.93']];
function MiniChart(){return <div className="chart"><div className="chart-grid"/><svg viewBox="0 0 700 210" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2f7dff" stopOpacity=".32"/><stop offset="1" stopColor="#2f7dff" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0,185 C60,175 80,120 145,132 S230,82 290,103 S380,53 445,72 S535,32 590,55 S655,24 700,36 L700,210 L0,210Z"/><path className="line" d="M0,185 C60,175 80,120 145,132 S230,82 290,103 S380,53 445,72 S535,32 590,55 S655,24 700,36"/></svg></div>}
function ReviewPage(){return <div className="page-content"><PageTop title="直播复盘" desc="用数据还原直播过程，快速发现下一场的增长机会" action="导出报告" icon={Download}/><div className="review-filters"><button><CalendarDays/>2026年8月28日<ChevronDown/></button><button>全部直播间<ChevronDown/></button></div><div className="kpi-row">{[[TrendingUp,'成交金额','¥12,847','+32.6%'],[Users,'累计观看','12,640','+18.2%'],[ShoppingCart,'成交订单','1,296','+24.5%'],[Activity,'AI触发成功率','96.8%','+3.2%']].map(([I,l,v,c])=><div key={l}><I/><span>{l}</span><strong>{v}</strong><em>{c} 较上场</em></div>)}</div><div className="review-grid"><section className="trend-panel"><div className="section-head"><b>直播趋势</b><span>在线人数 · 成交金额</span></div><MiniChart/></section><section className="insight-panel"><div className="section-head"><b>AI 复盘建议</b><Sparkles/></div><div className="score"><strong>86</strong><span>综合表现<br/><em>优于 78% 的直播场次</em></span></div>{['21:08 核心卖点讲解后转化明显提升','福利倒计时期间停留时长增加 26%','建议减少开场铺垫，提前 3 分钟上链接'].map((x,i)=><div className="insight" key={x}><span>{i+1}</span><p>{x}</p><ChevronRight/></div>)}</section></div><section className="table-panel"><div className="section-head"><b>历史直播</b><div className="search compact-search"><Search/><input placeholder="搜索场次"/></div></div><table><thead><tr><th>直播场次</th><th>直播时长</th><th>成交金额</th><th>订单数</th><th>ROI</th><th>状态</th><th/></tr></thead><tbody>{sessions.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===0?<><span className="session-icon"><Video/></span><strong>{x}</strong></>:x}</td>)}<td><span className="done-state"><i/>已完成</span></td><td><button className="text-btn">查看详情</button></td></tr>)}</tbody></table></section></div>}

const assetData=[['品牌开场视频.mp4','视频','86.4 MB','今天 10:32',Video,'#447eff'],['精华液产品主图.png','图片','2.8 MB','昨天 18:20',Image,'#2edbd2'],['直播间背景音乐.mp3','音频','8.3 MB','8月26日',Music,'#a875ff'],['美妆专场脚本.docx','文档','126 KB','8月25日',FileText,'#f3b53f'],['福利倒计时.mp4','视频','32.1 MB','8月24日',Video,'#447eff'],['品牌授权说明.pdf','文档','1.6 MB','8月22日',FileText,'#f3b53f']];
function AssetsPage(){const[type,setType]=useState('全部'),[uploaded,setUploaded]=useState(false);return <div className="page-content"><PageTop title="素材中心" desc="集中管理直播脚本、视频、图片和音频素材" action="上传素材" icon={Upload} onAction={()=>setUploaded(true)}/><div className="storage"><div><Folder/><span><strong>素材空间</strong><small>已使用 3.8 GB / 20 GB</small></span></div><div className="storage-bar"><i/></div><button>升级空间</button></div><div className="asset-toolbar"><div className="filter-tabs">{['全部','视频','图片','音频','文档'].map(x=><button className={type===x?'active':''} onClick={()=>setType(x)} key={x}>{x}</button>)}</div><div className="search"><Search/><input placeholder="搜索素材名称"/></div><button><SlidersHorizontal/>筛选</button></div><section className="asset-table"><table><thead><tr><th>素材名称</th><th>类型</th><th>大小</th><th>更新时间</th><th>使用状态</th><th/></tr></thead><tbody>{assetData.filter(a=>type==='全部'||a[1]===type).map(a=>{const I=a[4];return <tr key={a[0]}><td><span className="asset-icon" style={{color:a[5],background:a[5]+'16'}}><I/></span><strong>{a[0]}</strong></td><td>{a[1]}</td><td>{a[2]}</td><td>{a[3]}</td><td><span className="used">已就绪</span></td><td><button><MoreHorizontal/></button></td></tr>})}</tbody></table></section><div className="drop-zone"><Upload/><strong>拖拽文件到此处即可上传</strong><span>支持常用视频、图片、音频和文档格式，单个文件不超过 500 MB</span><button onClick={()=>setUploaded(true)}>选择文件</button></div>{uploaded&&<div className="toast"><Check/>素材已加入上传队列</div>}</div>}

function Toggle({on=true}){const[v,setV]=useState(on);return <button className={'toggle '+(v?'on':'')} onClick={()=>setV(!v)}><i/></button>}
function SettingsPage(){const[tab,setTab]=useState('账号与安全');const tabs=[['账号与安全',User],['直播设备',Mic2],['AI 默认设置',Bot],['通知设置',Bell],['版本与服务',RefreshCw]];return <div className="page-content"><PageTop title="设置" desc="管理账号、设备与应用偏好，让每次开播保持一致"/><div className="settings-layout"><section className="settings-nav">{tabs.map(([x,I])=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><I/>{x}<ChevronRight/></button>)}</section><section className="settings-panel"><div className="settings-title"><div><h3>{tab}</h3><p>统一管理你的云起慧播偏好与服务状态</p></div><button className="save"><Save/>保存更改</button></div>{tab==='账号与安全'&&<><div className="profile-row"><div className="profile-avatar">云</div><div><strong>头像</strong><span>支持 JPG、PNG，文件小于 5 MB</span></div><button>更换头像</button></div><div className="settings-form"><label>账号昵称</label><div className="field"><User/><input defaultValue="小云运营"/></div><label>绑定手机号</label><div className="field"><Smartphone/><input defaultValue="138****8000" disabled/><button>更换</button></div><SettingLine icon={LockKeyhole} title="登录密码" desc="建议每 90 天更换一次密码"><button>修改密码</button></SettingLine><SettingLine icon={ShieldCheck} title="登录保护" desc="新设备登录时需要短信验证"><Toggle/></SettingLine></div></>}{tab==='直播设备'&&<DeviceSettings/>}{tab==='AI 默认设置'&&<div className="settings-form"><label>默认音色</label><BigSelect icon={Bot} title="云汐·活力女声" desc="自然、亲切，适合美妆与生活类直播"/><label>响应模式</label><div className="choice-grid"><button className="selected"><Sparkles/><strong>智能响应</strong><small>根据场景自动判断回复时机</small></button><button><Zap/><strong>快速响应</strong><small>命中关键词后立即执行</small></button></div><SettingLine icon={Activity} title="自动执行动作" desc="AI 搭话时同步执行已配置的动作"><Toggle/></SettingLine></div>}{tab==='通知设置'&&<div className="settings-form">{[['开播提醒','直播间开播、结束及异常状态'],['AI 助手提醒','关键词未命中或动作执行失败'],['复盘报告','直播结束后生成数据复盘通知'],['产品更新','新功能与版本更新通知']].map((x,i)=><SettingLine key={x[0]} icon={Bell} title={x[0]} desc={x[1]}><Toggle on={i!==3}/></SettingLine>)}</div>}{tab==='版本与服务'&&<div className="settings-form"><div className="version-card"><Logo compact/><div><strong>云起慧播 2.0.0</strong><span>当前已是最新版本</span></div><button><RefreshCw/>检查更新</button></div>{['自动化服务','语音识别服务','AI 响应服务'].map((x,i)=><div className="service-row" key={x}><span><i/>{x}</span><b>运行正常</b><em>v{['1.3.2','2.1.0','2.0.4'][i]}</em></div>)}<button className="support"><Headphones/>联系在线客服</button></div>}</section></div></div>}
function SettingLine({icon:I,title,desc,children}){return <div className="setting-line"><div><I/><span><strong>{title}</strong><small>{desc}</small></span></div>{children}</div>}
function BigSelect({icon:I,title,desc}){return <button className="big-select"><I/><span><strong>{title}</strong><small>{desc}</small></span><ChevronDown/></button>}
function DeviceSettings(){return <div className="settings-form"><label>默认摄像头</label><BigSelect icon={Camera} title="USB Camera" desc="1920×1080 · 30 FPS"/><label>默认麦克风</label><BigSelect icon={Mic2} title="麦克风 (Realtek(R) Audio)" desc="输入电平正常"/><label>默认扬声器</label><BigSelect icon={Headphones} title="扬声器 (Realtek(R) Audio)" desc="系统默认设备"/><button className="device-test"><Play/>测试音频设备</button></div>}

const V1NAV=[[Users,'直播账号','accounts'],[Radio,'直播配置','config'],[Sparkles,'AI问答','qa'],[BarChart3,'直播复盘','review'],[User,'个人中心','profile'],[Settings,'设置','rules']];
function V1Top(){return <header className="v1-top"><Logo/><button className="start"><Play/>启动助手</button><Volume2/><div className="v1-volume"><i/></div><span>100%</span><SlidersHorizontal/><div className="window-mini">—　↗　×</div></header>}
function V1Side({page,setPage,onLogout}){return <aside className="v1-side"><nav>{V1NAV.map(([I,t,id])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><I/><span>{t}</span></button>)}</nav><div className="v1-user">用</div><button className="v1-exit" onClick={onLogout}><LogOut/>退出</button></aside>}
function PageTitle({children,desc,action}){return <div className="v1-title"><div><h2>{children}</h2>{desc&&<p>{desc}</p>}</div>{action&&<button className="v1-primary"><Plus/>{action}</button>}</div>}
function AccountsV1(){const platforms=[['抖音','douyin'],['微信视频号','wechat'],['淘宝','taobao'],['小红书','xiaohongshu'],['B站','bilibili'],['快手','kuaishou']];return <div className="v1-page accounts-page"><div className="platforms">{platforms.map(([name,icon],i)=><button className={i===0?'active':''} key={name}><span><img src={`/assets/platforms/${icon}.svg`} alt=""/></span>{name}</button>)}</div><PageTitle desc="为每个直播账号选择绑定的直播助手和互动账号，绑定后即可开播。" action="添加巨量百应直播账号">直播账号</PageTitle><div className="empty-account"><Radio/><span>该平台暂无直播账号</span></div><div className="account-divider"/><PageTitle desc="添加各平台互动账号，可被多个直播账号共享使用" action="添加抖音互动账号">互动账号</PageTitle><div className="empty-box">暂无互动账号</div></div>}
function ConfigV1(){const items=['暂停助播搭话','上车,321上链接','尺码','主播喝口水','备注加急发货','还剩几单','踢单倒计时','闭眼冲','划不划算'];return <div className="config-v1"><div className="config-tools"><button>示例助手 <ChevronDown/></button><button><Plus/></button><button><Download/></button><button><Upload/></button><button className="host"><User/>选择主播</button></div><div className="config-tabs"><b>AI助播</b><b>AI中控</b></div><div className="config-body"><section className="phrase-list"><div className="v1-search"><Search/>搜索搭话...</div><span className="expand">全部展开</span>{items.map((x,i)=><article className={i===1?'selected':''} key={x}><strong>{x}</strong>{i===0&&<em>默认·不可删除</em>}{i===1&&<><small>助播 1</small><p>下方小黄车1号链接，价格已开，喜欢直接拍！</p></>}</article>)}</section><section className="phrase-editor"><PageTitle action="保存配置">AI助播配置 · 上车,321上链接</PageTitle><div className="v1-card"><h3>触发词 <span>命中即触发本条搭话</span></h3><div className="trigger-row"><b>上车　×</b><b>321上链接　×</b><input placeholder="输入触发词后按回车添加"/></div></div><div className="v1-card"><h3>助播搭话 <span>共 1 条搭话</span></h3><div className="talk-row"><div><b>助播 1</b>　音色: <strong>依依</strong>　倍速: <strong>1X</strong><p>下方小黄车1号链接，价格已开，喜欢直接拍！</p></div><button>删除</button><button className="v1-primary">编辑</button><button>▶ 试听</button></div><button className="add-talk">＋ 添加搭话</button></div></section></div></div>}
function QaV1(){return <div className="qa-v1"><aside><button className="v1-primary">＋ 创建新的对话</button><span>暂无对话记录</span></aside><main><Sparkles/><h1>你好，我是 <b>慧播 AI</b></h1><p>描述你的直播需求，帮你生成脚本、话术、解读平台规则</p><div className="ask-box">请输入您的问题...<Send/></div><h3>你可以试试</h3><div className="qa-cards">{[['生成一个直播间的脚本','按开场、互动、产品、催单结构生成通用带货脚本'],['抖音直播的详细规则','了解抖音直播的违规红线与话术合规要点'],['视频号直播的相关规则','掌握视频号直播的开播条件与运营规范']].map(x=><article key={x[0]}><FileText/><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></main></div>}
function ProfileV1(){return <div className="v1-page"><PageTitle>个人中心</PageTitle><div className="profile-grid-v1"><main><section className="profile-user"><div>用</div><h3>用户2768　✎</h3><p>账户类型　<span>个人用户</span></p></section><section className="profile-password"><LockKeyhole/><div><b>登录密码</b><p>建议定期修改密码以保障账户安全</p></div><button>设置密码</button></section><section className="invite"><h3>• 我的邀请码</h3><b>5rh8u5do</b><button>复制</button><p>已邀请 0 人</p><div className="qr">▦</div></section></main><aside><section><h3>• 系统更新</h3><div className="service"><RefreshCw/><div><b>应用版本</b><p>当前已是最新版本</p></div><em>● 已是最新</em></div></section><section><h3>• 组件服务　 <small>⟳ 刷新</small></h3>{[['自动化服务','V1.2.1'],['语音识别服务','V1.0.5'],['极速语音识别模型','V1.0.0']].map(x=><div className="service" key={x[0]}><div><b>{x[0]}　<span>运行中</span></b><p>{x[1]}</p></div><em>● 运行中　⇩</em></div>)}</section></aside></div></div>}
function RulesV1(){return <div className="v1-page rules-v1"><div className="rule-tabs">{['替换词管理','弹幕配置','违禁词配置','音色管理','互动管理'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="info-banner">ⓘ　配置中文语音识别替换词规则，用于修正语音识别中的常见误识别词汇。源词会被自动替换为目标词，留空目标词表示忽略该识别结果。　×</div><div className="industries">行业分类：　{['美妆','食品','服装','3C数码','家居日用','母婴','珠宝饰品','农副产品','修改'].map(x=><button key={x}>{x}</button>)}</div><div className="rules-tools"><div className="v1-search"><Search/>搜索替换词</div><button>批量添加</button><button className="v1-primary">＋ 新增替换词</button></div><div className="rules-table"><header><span>#　　源词（识别词）</span><span>替换为</span><span>操作</span></header><div>暂无替换词规则，点击右上角添加</div></div><p>共 0 条替换词规则</p></div>}
function FeedbackV1(){return <div className="v1-page feedback-v1"><PageTitle>意见反馈</PageTitle><div className="v1-card"><h3>告诉我们您遇到的问题或建议</h3><textarea placeholder="请输入您的反馈内容..."/><div className="feedback-actions"><button>上传截图</button><button className="v1-primary">提交反馈</button></div></div></div>}
function Shell({onLogout}){const[page,setPage]=useState('accounts');return <div className="v1-shell"><V1Top/><V1Side page={page} setPage={setPage} onLogout={onLogout}/><div className="v1-main">{page==='accounts'?<AccountsV1/>:page==='config'?<ConfigV1/>:page==='qa'?<QaV1/>:page==='review'?<ReviewPage/>:page==='profile'?<ProfileV1/>:<RulesV1/>}</div><button className="chat-float"><FileText/></button></div>}
function App(){const[auth,setAuth]=useState(false),[mode,setMode]=useState('login');return auth?<Shell onLogout={()=>setAuth(false)}/>:<AuthV2 mode={mode} setMode={setMode} onSuccess={()=>setAuth(true)}/>}
createRoot(document.getElementById('root')).render(<App/>);
